name: Deploy canary

on: 
  workflow_dispatch:
    inputs:
      metric_type:
        description: '"sleep"/"error"'
        required: true
        default: 'error'
      amount:
        description: '"unit"'
        required: true
        default: '0'
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Login to registry
        run: | 
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin 

      - name: Build and tag docker image
        run: |
          docker build . --tag \
          gustavolopess/nestjs-canary-demo:${{ github.sha }}

      - name: Push image to docker hub 
        run: docker push gustavolopess/nestjs-canary-demo:${{ github.sha }}

  generate-deployment:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployer repository
        uses: actions/checkout@v2
        with:
          repository: gustavolopess/k8s-canary-demo
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create new deployment
        env:
          CLUSTER_HOST: https://ec2-3-80-38-40.compute-1.amazonaws.com:8443
          SERVICEACCOUNT_TOKEN: ${{ secrets.SERVICEACCOUNT_TOKEN }}
          NAMESPACE_SERVICEACCOUNT: ${{ secrets.NAMESPACE_SERVICEACCOUNT }}
        run: |
          python deployment_generator.py nestjs-canary-demo nestjs-canary-demo gustavolopess/nestjs-canary-demo ${{ github.sha }}

      - name: Analyze new canary
        env:
          CLUSTER_HOST: https://ec2-3-80-38-40.compute-1.amazonaws.com:8443
          SERVICEACCOUNT_TOKEN: ${{ secrets.SERVICEACCOUNT_TOKEN }}
          NAMESPACE_SERVICEACCOUNT: ${{ secrets.NAMESPACE_SERVICEACCOUNT }}
          METRIC_TYPE: ${{ github.event.inputs.metric_type }}
          AMOUNT: ${{ github.event.inputs.amount }}
        shell: bash
        run: |
          if [ "$METRIC_TYPE" == "" ] && [ "$AMOUNT" == "" ]; then
            APPLICATION_URL="http://ec2-3-80-38-40.compute-1.amazonaws.com:8080/error/0" python3 canary_monitor.py 
          else
            APPLICATION_URL="http://ec2-3-80-38-40.compute-1.amazonaws.com:8080/$METRIC_TYPE/$AMOUNT" python3 canary_monitor.py
          fi
          
