name: Deploy canary

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Login to registry
        run: | 
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | \
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin 

      - name: Build and tag docker image
        run: |
          docker build . --tag \
          gustavolopess/nestjs-canary-demo:${{ github.sha }}

      - name: Push image to docker hub 
        run: docker push gustavolopess/nestjs-canary-demo:${{ github.sha }}

  generate-deployment:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployer repository
        uses: actions/checkout@v2
        with:
          repository: gustavolopess/k8s-canary-demo
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create and analyze new canary
        env:
          CLUSTER_HOST: ${{ secrets.CLUSTER_HOST }}
          SERVICEACCOUNT_TOKEN: ${{ secrets.SERVICEACCOUNT_TOKEN }}
          NAMESPACE_SERVICEACCOUNT: ${{ secrets.NAMESPACE_SERVICEACCOUNT }}
          APPLICATION_URL: ${{ secrets.APPLICATION_URL }} 
        run: |
          python deployment_generator.py nestjs-canary-demo nestjs-canary-demo gustavolopess/nestjs-canary-demo ${{ github.sha }} \
          && python3 canary_monitor.py 
